name: Liquibase Database Migration on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  liquibase-migration:
    runs-on: windows-latest

    env:
      DB_NAME: testdb
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_ROOT_PASSWORD: root_password
      DB_URL: jdbc:mysql://127.0.0.1:3306/testdb

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MySQL
      run: |
        choco install mysql --params "/INSTALLDIR:C:\mysql" -y
        mysql --version

    - name: Configure MySQL
      run: |
        # Start MySQL service
        sc start MySQL
        timeout /t 10

        # Secure MySQL and set root password
        echo ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_ROOT_PASSWORD}'; | mysql -u root
        echo CREATE DATABASE ${DB_NAME}; | mysql -u root -p${DB_ROOT_PASSWORD}
        echo CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}'; | mysql -u root -p${DB_ROOT_PASSWORD}
        echo GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost'; | mysql -u root -p${DB_ROOT_PASSWORD}
        echo FLUSH PRIVILEGES; | mysql -u root -p${DB_ROOT_PASSWORD}

    - name: Set up Liquibase
      run: |
        curl -Lo liquibase.zip https://github.com/liquibase/liquibase/releases/download/v4.29.1/liquibase-4.29.1-windows-x64.zip
        tar -xf liquibase.zip -C C:\

    - name: Download MySQL JDBC Driver
      run: |
        curl -Lo liquibase\lib\mysql-connector-java-8.0.26.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar

    - name: Run Liquibase Migrations
      run: |
        C:\liquibase\liquibase.bat --defaultsFile=liquibase/liquibase.properties update
